# Generated by Django 6.0.1 on 2026-01-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specs', models.TextField()),
                ('description', models.JSONField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.JSONField()),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_product',
            },
        ),
    ]
