# Generated by Django 6.0.1 on 2026-01-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='account_product',
        ),
    ]
